server:
  port: 8089

spring:
    application:
        name: admin
    datasource:
        url: jdbc:mysql://47.106.117.240:3306/hmx_schema
        username: root
        password: 1234
        # 使用druid数据源
        #type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
    freemarker:
      allow-request-override: false
      cache: false
      check-template-location: true
      charset: UTF-8
      content-type: text/html
      expose-request-attributes: false
      expose-session-attributes: false
      expose-spring-macro-helpers: false
      suffix: .html
    servlet:
      multipart:
        max-file-size : 1024mb
        max-request-size : 1589mb

logging:
  file: admin.log
  path: /logs

mybatis:
  mapper-locations: classpath*:com/hmx/*/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
#黄梅戏短信接入配置
SMSSendUrl: http://jk.106api.cn/smsUTF8.aspx
SMSUserName: hmx008
SMSPassword: F11A3E1A905E68D15C8FCA6DFD022630
SMSGwid: b89c4aec
SMSVerificationTemplate: "【黄梅戏资源库】您的验证码是code，请在一分钟内进行验证!"
#        filters: stat
#        maxActive: 20
#        initialSize: 1
#        maxWait: 60000
#        minIdle: 1
#        timeBetweenEvictionRunsMillis: 60000
#        minEvictableIdleTimeMillis: 300000
#        validationQuery: select 'x'
#        testWhileIdle: true
#        testOnBorrow: false
#        testOnReturn: false
#        poolPreparedStatements: true
#        maxOpenPreparedStatements: 20

#阿里oos accessKeyId accessKeySecret
accessKeyId: LTAIaeZo5lNZpDBd
accessKeySecret: HSB7GdPp998ziaGiVK6rgbrHhHSwAl
imageType: default
#默认png
imageExt: png,jpg,jpeg,gif
videoExt: MP4,TS,3GP,MPG,MPEG,MPE,DAT,VOB,ASF,AVI,WMV,ASF,FLV,F4V,RM,RMVB,MOV,MKV,M3U8,DV,GIF,M2T,M4V,MJ2,MJPEG,MTS,OGG,QT,SWF,WEBM
#阿里文件上传：pdf,epub
oss: 
  endpoint: http://oss-cn-hangzhou.aliyuncs.com
  accessKeyId: LTAIk9cA9ccLsyak
  accessKeySecret: LN0d98MfMdc8WJb8qsBmlEaTNLaoq6
  bucketName: zhonghuazhu
  ossIsFormal: false
  physicsrootpath: C:\\files
  serverip: https://zhonghuazhu.oss-cn-hangzhou.aliyuncs.com
