server:
  port: 8090
spring:  
  datasource:
    url: jdbc:mysql://47.106.117.240:3306/hmx_schema
    username: root  
    password: 1234  
    driver-class-name: com.mysql.jdbc.Driver
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
  jmx:
    enabled: false
        
mybatis:
  mapper-locations: classpath*:com/hmx/*/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
#黄梅戏短信接入配置
SMSSendUrl: http://jk.106api.cn/smsUTF8.aspx
SMSUserName: hmx008
SMSPassword: F11A3E1A905E68D15C8FCA6DFD022630
SMSGwid: b89c4aec
SMSVerificationTemplate: "【黄梅戏资源库】您的验证码是code，请在一分钟内进行验证!"

#阿里oos accessKeyId accessKeySecret
accessKeyId: LTAIaeZo5lNZpDBd
accessKeySecret: HSB7GdPp998ziaGiVK6rgbrHhHSwAl
imageType: default
#默认png
imageExt: png,jpg,jpeg,gif
videoExt: MP4,TS,3GP,MPG,MPEG,MPE,DAT,VOB,ASF,AVI,WMV,ASF,FLV,F4V,RM,RMVB,MOV,MKV,M3U8,DV,GIF,M2T,M4V,MJ2,MJPEG,MTS,OGG,QT,SWF,WEBM
    